using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SpaceStationTycoon.Gameplay
{
    public interface IModule
    {
        /// How many units does this Module take up
        int Units { get; }

        /// Tier of this module
        int Tier { get; }

        /// Does this module need to be built outside
        bool IsExternal { get; }

        /// What is the base Credit price for this module
        double BasePrice { get; }

        /// Unique identifier (use a hashCode generated by unique name)
        int Identifier { get; }

        string DisplayStatus { get; }

        void Update(double deltaTimeSeconds);
    }
}
